#!/usr/bin/env zsh

ALT_FOLDER=.dropbox-alt
ALT_HOME=/Users/$USER/$ALT_FOLDER

# Use mdfind to find Dropbox.app
for a in `mdfind Dropbox.app`;
do
    if [[ -d $a ]]; then
        HOME=$ALT_HOME $a/Contents/MacOS/Dropbox
    fi
done
